---
title: "p8130_final"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(arsenal)
library(MASS)
library(HH)
library(leaps)
library(corrplot)
library(broom)
df = read.csv("./data/Lawsuit.csv")%>%
  janitor::clean_names()
```
# descriptive table of data

```{R}
tableby(gender~sal94+sal95+prate+exper ,data=df,test=FALSE,numeric.stas=c("meansd","median","iqr"))%>%
  summary(text=TRUE)

```

# data distribution,
```{r}

ggplot(aes(x=sal94),data=df)+geom_density()
ggplot(aes(x=sal95),data=df)+geom_density()

```


# transformation
```{r}
fit_0=lm(sal94~factor(dept)+factor(gender)+factor(clin)+factor(cert)+prate+exper+factor(rank),data=df)

boxcox(fit_0,data=df)
df=
  df %>%
  mutate(ln94=log(sal94),
         ln95=log(sal95))
ggplot(aes(x=ln94),data=df)+geom_density()
ggplot(aes(x=ln95),data=df)+geom_density()
fit_1 = lm(ln94~factor(dept)+factor(gender)+factor(clin)+factor(cert)+prate+exper+factor(rank),data=df)
summary(fit_1)
fit_1.1 = lm(ln95~factor(dept)+factor(gender)+factor(clin)+factor(cert)+prate+exper+factor(rank),data=df)
summary(fit_1.1)

```
# interaction
```{r}
df%>%
  dplyr::select(-id,-sal94,-sal95,-ln94,-ln95)%>%
  pairs()
fit_2 = lm(ln94~factor(dept)*factor(gender)+factor(clin)+factor(cert)+prate+exper+factor(rank),data=df)
anova(fit_1,fit_2)
fit_3 = lm(ln94~factor(gender)*factor(clin)+factor(dept)+factor(cert)+prate+exper+factor(rank),data=df)
fit_4 = lm(ln94~factor(gender)*factor(cert)+factor(dept)+factor(clin)+prate+exper+factor(rank),data=df)
fit_5 = lm(ln94~factor(gender)*prate+factor(dept)+factor(clin)+factor(cert)+exper+factor(rank),data=df)
fit_6= lm(ln94~factor(gender)*exper+factor(dept)+factor(clin)+factor(cert)+prate+factor(rank),data=df)
fit_7 = lm(ln94~factor(gender)*factor(rank)+factor(dept)+factor(clin)+factor(cert)+prate+exper,data=df)
fit_8 = lm(ln95~factor(dept)*factor(gender)+factor(clin)+factor(cert)+prate+exper+factor(rank),data=df)
anova(fit_1,fit_2)
fit_9 = lm(ln95~factor(gender)*factor(clin)+factor(dept)+factor(cert)+prate+exper+factor(rank),data=df)
fit_10 = lm(ln95~factor(gender)*factor(cert)+factor(dept)+factor(clin)+prate+exper+factor(rank),data=df)
fit_11 = lm(ln95~factor(gender)*prate+factor(dept)+factor(clin)+factor(cert)+exper+factor(rank),data=df)
fit_12= lm(ln95~factor(gender)*exper+factor(dept)+factor(clin)+factor(cert)+prate+factor(rank),data=df)
fit_13 = lm(ln95~factor(gender)*factor(rank)+factor(dept)+factor(clin)+factor(cert)+prate+exper,data=df)

anova(fit_1,fit_3)
anova(fit_1,fit_4)
anova(fit_1,fit_5)
anova(fit_1,fit_6)
anova(fit_1,fit_7)
anova(fit_1.1,fit_8)
anova(fit_1.1,fit_9)
anova(fit_1.1,fit_10)
anova(fit_1.1,fit_11)
anova(fit_1.1,fit_12)
```
interaction of rank and exper

# confonder
```{r}
fit1 = lm(ln94~factor(gender),data=df)
fit2 = lm(ln94~factor(gender)+factor(dept),data=df)
fit3 = lm(ln94~factor(gender)+factor(clin),data=df)
fit4 = lm(ln94~factor(gender)+factor(cert),data=df)
fit5 = lm(ln94~factor(gender)+prate,data=df)
fit6 = lm(ln94~factor(gender)+exper,data=df)
fit7 = lm(ln94~factor(gender)+factor(rank),data=df)
fit8 = lm(ln95~factor(gender),data=df)
fit9 = lm(ln95~factor(gender)+factor(dept),data=df)
fit10= lm(ln95~factor(gender)+factor(clin),data=df)
fit11 = lm(ln95~factor(gender)+factor(cert),data=df)
fit12 = lm(ln95~factor(gender)+prate,data=df)
fit13 = lm(ln95~factor(gender)+exper,data=df)
fit14 = lm(ln95~factor(gender)+factor(rank),data=df)
model_name = c("fit1","fit2","fit3","fit4","fit5","fit6","fit7","fit8","fit9","fit10","fit11","fit12","fit13","fit14")
rbind(
  tidy(fit1)[2,2],
  tidy(fit2)[2,2],
  tidy(fit3)[2,2],
  tidy(fit4)[2,2],
  tidy(fit5)[2,2],
  tidy(fit6)[2,2],
  tidy(fit7)[2,2],
  tidy(fit8)[2,2],
  tidy(fit9)[2,2],
  tidy(fit10)[2,2],
  tidy(fit11)[2,2],
  tidy(fit12)[2,2],
  tidy(fit13)[2,2],
  tidy(fit14)[2,2]
  )%>%
  cbind(model_name)%>%
  dplyr::select(model_name,estimate)%>%
  knitr::kable()
```
dept and prate are confonder
# model selection

```{r}
fit_94=lm(ln94~factor(gender)*factor(rank)+factor(dept)+prate,data=df)
fit_95=lm(ln95~factor(gender)*factor(rank)+factor(dept)+prate,data=df)
plot(fit_94)
plot(fit_95)

```

# model diagnosis
















```{r}


```